server:
  port: 8087

spring:
  application:
    name: command-side-shipment
  kafka:
    bootstrapServers: localhost:9092
    producer:
      retries: 3
      bootstrapServers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-Serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: poc-es