version: "3.9"
services:
  order-command:
    image: openjdk:19-slim
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    depends_on:
      - kafka
    env_file:
      - ./config/.env.docker
    volumes:
      - "../:/app"
    ports:
      - "8081:8081"
    working_dir: /app
    command: java -jar order/command-side/build/libs/command-side-0.0.1-SNAPSHOT.jar
  order-query:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    depends_on:
      - kafka
    image: openjdk:19-slim
    ports:
      - "8083:8083"
    env_file:
      - ./config/.env.docker
    volumes:
      - "../:/app"
    working_dir: /app
    command: java -jar order/query-side/build/libs/query-side-0.0.1-SNAPSHOT.jar