version: "3.9"
services:
  shipment-command:
    image: openjdk:19-slim
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    depends_on:
      - kafka
    env_file:
      - ./config/.env.docker
    volumes:
      - "../:/app"
    ports:
      - "10081:10081"
    working_dir: /app
    command: java -jar shipment/command-side/build/libs/command-side-0.0.1-SNAPSHOT.jar
  shipment-query:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    depends_on:
      - kafka
    image: openjdk:19-slim
    ports:
      - "10083:10083"
    env_file:
      - ./config/.env.docker
    volumes:
      - "../:/app"
    working_dir: /app
    command: java -jar shipment/query-side/build/libs/query-side-0.0.1-SNAPSHOT.jar