version: "3"
services:
  kafka:
    image: 'bitnami/kafka:${KAFKA_TAG:-latest}'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - LOG_RETENTION_HOURS=1
