version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:${ZOOKEEPER_TAG:-latest}'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - espoc
  kafka:
    image: 'bitnami/kafka:${KAFKA_TAG:-latest}'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST:-127.0.0.1}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - LOG_RETENTION_HOURS=26280
    depends_on:
      - zookeeper
    networks:
      - espoc

networks:
  espoc: