server:
  port: 10083

spring:
  application:
    name: query-side-shipment
  profiles:
    include:
      - observe
      - cluster
      - query-side
      - kafka
      - kafka-producer
      - kafka-consumer