global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'cluster-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          namespace: 'event-sourcing'
          app: 'order-command'
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          namespace: 'event-sourcing'
          app: 'order-handler'
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          namespace: 'event-sourcing'
          app: 'order-query'
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          namespace: 'event-sourcing'
          app: 'payment-command'
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          namespace: 'event-sourcing'
          app: 'payment-handler'
      - targets: [ 'host.docker.internal:8086' ]
        labels:
          namespace: 'event-sourcing'
          app: 'payment-query'
      - targets: [ 'host.docker.internal:8087' ]
        labels:
          namespace: 'event-sourcing'
          app: 'shipment-command'
      - targets: [ 'host.docker.internal:8088' ]
        labels:
          namespace: 'event-sourcing'
          app: 'shipment-handler'
      - targets: [ 'host.docker.internal:8089' ]
        labels:
          namespace: 'event-sourcing'
          app: 'shipment-query'
