cluster:
  order:
    command:
      base-url: http://${CLUSTER_HOST:localhost}:8000/oc/
    query:
      base-url: http://${CLUSTER_HOST:localhost}:8000/oq/
  payment:
    command:
      base-url: http://${CLUSTER_HOST:localhost}:9081
    query:
      base-url: http://${CLUSTER_HOST:localhost}:9083
  shipment:
    command:
      base-url: http://${CLUSTER_HOST:localhost}:10081
    query:
      base-url: http://${CLUSTER_HOST:localhost}:10083
