server:
  port: 8081

spring:
  application:
    name: order-command-side
  profiles:
    include: "observe, cluster, mock, kafka, kafka-producer, redis, idempotency"
    active:
      - development
      - docker-support