server:
  port: 8081

spring:
  application:
    name: order-command-side
  profiles:
    include:
      - observe
      - cluster
      - kafka
      - kafka-producer
      - redis
      - idempotency

