server:
  port: 8083

spring:
  application:
    name: order-query-side
  profiles:
    include:
      - observe
      - cluster
      - query-side
      - kafka
      - kafka-producer
      - kafka-consumer
