name: Gradle try build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build Image with Jib
        run: ./gradlew jib -Djib.to.tags=$GITHUB_REF_NAME,'latest' -Djib.to.auth.username=${REGISTRY_USER} -Djib.to.auth.password=${REGISTRY_PASSWORD}
