name: E2E Test

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

      - name: Run The Cluster
        run: docker compose -f Docker/boot-run-apps-docker-compose.yml -f Docker/kafka-docker-compose.yml --env-file Docker/config/.env.docker -p event-sourcing up -d

      - name: Check the order-query
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:8083/actuator/health
          max-attempts: 6
          retry-delay: 10s
          retry-all: true

      - name: Check the order-command
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:8081/actuator/health
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - name: run Postman Collection
        uses: matt-ball/newman-action@master
        with:
          collection: postman/OrderCommand.postman_collection.json

      - name: clean docker compose
        if: always()
        run: |
          docker compose -f Docker/boot-run-apps-docker-compose.yml -f Docker/kafka-docker-compose.yml --env-file Docker/config/.env.docker -p event-sourcing down
