server:
  port: 9083

spring:
  application:
    name: payment-query-side
  profiles:
    include:
      - observe
      - cluster
      - query-side
      - kafka
      - kafka-producer
      - kafka-consumer